# Generated by Django 4.1.3 on 2022-12-10 06:22

import chunk_it.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_files/', validators=[chunk_it.validators.validate_file_size, chunk_it.validators.validate_extension])),
                ('size_num', models.FloatField(null=True)),
                ('size_string', models.CharField(choices=[('B', 'B'), ('KB', 'KB'), ('MB', 'MB'), ('GB', 'GB')], default='B', max_length=10)),
                ('file_type', models.CharField(choices=[('.json', 'Json'), ('.csv', 'Csv')], default='.csv', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='File_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='newFile', max_length=300)),
                ('file', models.FileField(upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
