# Generated by Django 4.1.3 on 2022-12-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunk_it', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk_file',
            name='size_string',
            field=models.CharField(choices=[('KB', 'KB'), ('MB', 'MB'), ('GB', 'GB')], default='KB', max_length=10),
        ),
    ]
